language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: DCzCkXQDMXgmrG2w/XaYXjmno3oYERwcw2CwhwyMzVzER26dlysAXCj+udeHtLPqk6606NbsO+sHyv7Y3zMSc0onqxHG53RGOMADvAPNIFNSd785CirTWAvhS2qDkiA72Pxzr8ZLMyMhhuwql6eorAgzPUX7Ct06ebo5boy94BwMVhSSGZ2InCBX+9a4b7Y+E8q+P69lqw9z3VRr3ytaG+5MWgOIAIUPORwHUvujpNscf1AtIfk5RUTm3O7t1ToH5T2IlJJZUrvMlV0zlhHHvBIaShdICAkz8xuMOEDBNcDAfAjSfpz3o5cDzRygECBfuuy29ceAFFXb7dXz2eRmnAH+fA5USLEJvp8tsvI8W91m9Wies37dHhooLW42DQ/VkV9e4GhrbGM4NY3Xb09cLSgMT7J1BGcZhr+kuQmCWE+1AfHSURhXYlQoeddh/SiTacGvQP+ua6UXV+HmQ9wALYGR9DlDDWZMvwG1Z6iDU6eI3HHZ6rURJfGl2p66EGmkDtqxaEkNtGncAqZvgAPVgzPRNnM/TNJmWxVmTKI2kx9O2YRFdJ/ejsEMaoVtF4+C4wY014XBrAdlnPm30F4cxXwqP+JPvrtJslykwMPYi3HZhJXsK5L+D2CK1iRNd0CLYFcNGFnSPgpxG8xghoBlHEumIv+7ObTJu03+BtMArBU=
  app: secure-caverns-67680
  on:
    repo: coreyjhighland/TakeMeThere
